### ISSUE TITLE
Implement Unit Tests

### ISSUE THREAD

**Issue by alercunha** [zbra-solutions/android-linq#2]
A unit test for each method is absolutely necessary!

**Comment by brunovinicius** [comment]
Unit test covering all methods have been implemented. Can you make your request more clear?

**Comment by alercunha** [comment]
What's the current code coverage of the unit tests implemented? Does it cover all LINQ methods?

**Comment by brunovinicius** [comment]
I think they do

**Comment by alercunha** [comment]
I'll close the ticket but it would be good to add how much coverage (%) is currently supported.
