### ISSUE TITLE
Add max() and min()

### ISSUE THREAD

**Issue by brunovinicius** [zbra-solutions/android-linq#21]
Add function to get max() and min() values of a collection

```
<TKey> T max(Selector<T, TKey> selector, Comparator<TKey> comparator);
<TKey extends Comparable<TKey> T max(Selector<T, TKey> selector);

<TKey> T min(Selector<T, TKey> selector, Comparator<TKey> comparator);
<TKey extends Comparable<TKey> T min(Selector<T, TKey> selector);
```

**Comment by royben** [comment]
I see there has been a long time since there was an update, but I still don't see any min() and max().
Is there any reason? or am I just not using the latest package ?

Thanks!

**Comment by brunovinicius** [comment]
@royben happy to know theres still people using this =) I will try to up a new version with these methods available this week. Just a heads up: if you starting a new project now, using kotlin might solve the issues this lib tries to address and many more. Cheers!

**Comment by royben** [comment]
Thanks!

בתאריך 25 ביול' 2017 03:57,‏ "Bruno Vinicius" <notifications@github.com>
כתב:
