### ISSUE TITLE
Add new contains() method

### ISSUE THREAD

**Issue by sflanders** [zbra-solutions/android-linq#25]
Awesome library.  Coming from the .net world i pretty dependent on linq.   Please add method to do a **contains()** on a predicate.  Obviously you can use **firstOrDefault()** and check for null but would be great to have a real function.

```
boolean contains(Selector<T, TResult> selector) {
   // see if the element exists
}
```

**Comment by brunovinicius** [comment]
Thanks for the feedback. We've been on out of office for Christmas and new years and just been back. We'd definitely take a look at it and release it in the next version =)
