### ISSUE TITLE
The method sum not working just with sum(c->c.fieldToSum)

### ISSUE THREAD

**Issue by iFernandoSousa** [zbra-solutions/android-linq#26]
/**
*I Try use sum method, but this not working just with sum(c->c.fieldToSum).
*This way the code not compile and I need change, create a new class and implement SelectorInteger 
*Interface for each field I want to Sum, I think this is not useful, is possible to use field directly some like
*another methods select or orderby allow. 
- thanks.
  */

package br.com.example;

import android.support.test.rule.ActivityTestRule;
import android.support.test.runner.AndroidJUnit4;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.ArrayList;
import java.util.List;

import br.com.zbra.androidlinq.delegate.SelectorInteger;

import static br.com.zbra.androidlinq.Linq.stream;

@RunWith(AndroidJUnit4.class)
public class LinqDemoTest {
    @Rule
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(MainActivity.class);

```
private List<NotWorking> notWorkingList;

public LinqDemoTest() {
    notWorkingList = new ArrayList<>();
    notWorkingList.add(new NotWorking(1, "A"));
    notWorkingList.add(new NotWorking(2, "B"));
    notWorkingList.add(new NotWorking(3, "C"));
}

@Test
public void testSumNotCompile() {
    //The android compile not found c.fieldToSum inside the sum method
    int total = stream(notWorkingList).sum(c -> c.fieldToSum);
    assert total == 6;
}

@Test
public void testSumWorkingButConfused() {
    //This way work, but is a little bit confused to create a new class and extend the interface for each field I want to sum.
    int total = stream(notWorkingList).sum(new NotWorking.SumField());
    assert total == 6;
}

public static class NotWorking {
    public int fieldToSum;
    public String anotherField;

    public NotWorking(int field, String another) {
        this.fieldToSum = field;
        this.anotherField = another;
    }

    public static class SumField implements SelectorInteger<NotWorking> {
        @Override
        public Integer select(NotWorking value) {
            return value.fieldToSum;
        }
    }
}
```

}

**Comment by brunovinicius** [comment]
Hello!

I made some tests and concluded that for some reason the Java compiler cannot infer the correct type if you use the simplest lambda form 

```
(c) -> c.intField
```

Meanwhile you can use one of the following forms and it will work like a charm (I would go for the first one, btw):
- by explicitly typing the lambda parameter

```
(NotWorking c) -> c.fieldToSum
```
- or by casting the whole thing to the appropriate Selector

```
(SelectorInteger<NotWorking>) (c) -> c.fieldToSum
```

This is probably related to sum() having 7 overrides... need to check if there's any way to mitigate this further.

Also, this should probably be in some FAQ or something...

**Comment by iFernandoSousa** [comment]
Thank you Bruno, casting the c works perfectly. 

sum((NotWorking c) -> c.fieldToSum)
