### ISSUE TITLE
stream problem

### ISSUE THREAD

**Issue by danponce** [zbra-solutions/android-linq#27]
Hi!
First of all, thanks for the library! I don´t know what is a stream on the examples given.  Can you give me a better example for the ones that are starting to know LINQ?

**Comment by brunovinicius** [comment]
Hi! You mean you want me to improve the readme.md? Give a brief intro to Streams there maybe. Might be cool =)

**Comment by danponce** [comment]
The thing is that I'm trying to implement your example but stream is not recognized, do you know why?

**Comment by brunovinicius** [comment]
Did you make a static import?

```
static import br.com.zbra.androidlinq.Linq.*
```
