### ISSUE TITLE
Android Studio 4.0 Upgrade

### ISSUE THREAD

**Issue by ghost** [zbra-solutions/android-linq#29]
Getting `Failed to resolve: br.com.zbra:android-linq:1.1.0`
With the latest version of Android Studio with latest version of gradle.

Android Gradle Plugin Version: 4.0.0
Gradle Version: 6.4.1

I know it's an old lib, that's not needed by the masses any more due to java.streams, but unfortunately for me, I am developing an app that needs to work on Android 6!

**Comment by brunovinicius** [comment]
Hello!

Did you add JCenter to your buildscript repositories section?

````
buildscript { 
    repositories {
        jcenter()
    }
    ...
}
````

At any rate, I would recommend maybe trying an alternative like RxJava which will provide better support and its more powerful and modern by today's standards.

**Comment by ghost** [comment]
Yes added it, the lib works perfect for what I want, up until the android studio 4.0 release this weekend. Already have quite a big list of apps for this business made using this lib within them, so would like to keep it working.

**Comment by brunovinicius** [comment]
Great! Nice to know. Have a good one! Closing.

**Comment by ghost** [comment]
Sorry, I think my message may have been unclear. It's not resolved, I have had that in the app all the time, it is still failing with it in.

**Comment by brunovinicius** [comment]
Oh, ok. Will give it a look, but the Android Studio version should not interfere. Will let you know if I find anything.

**Comment by brunovinicius** [comment]
I found this on StackOverflow https://stackoverflow.com/questions/47760395/android-studio-does-not-import-dependency-from-jcenter-or-maven-central

Had new comments a few days ago (may 28) recommending the removal of mavencentral() from repositories. Maybe its linked. Not sure if this may be your issue, but its worth a try.

**Comment by ghost** [comment]
I don't have mavencentral, build.gradle here... my phone is removing line spacing from the code, apologies about that 😕

```common to all sub-projects/modules.
buildscript {
repositories {
google()
jcenter() }

dependencies {
classpath 'com.android.tools.build:gradle:3.6.3'
classpath 'com.google.gms:google-services:4.3.3'
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.1.0'
// NOTE: Do not place your application dependencies here; they belong
// in the individual module build.gradle files } }
allprojects {
repositories {
google()
jcenter() } }
task clean(type: Delete) {
delete rootProject.buildDir }```

**Comment by ghost** [comment]
I have removed my project dependency on this lib, thanks for suggesting RxJava for it alternatively, looked into it, and the method for using it is nice.

Only thing is, the syntax for this lib was very nice and readable, and very little code for it, but can't win everything!

**Comment by brunovinicius** [comment]
Hey,tks for the kind words. I put some time into finding out what was missing but I could not put my finger on it. Seems like its not actually published to JCenter, but to Spring and for some reason, that doesnt cut it anymore. I will update this issue if I can find the solution.

Good luck going forward. RxJava is a great lib and there are extensions made specifically for Android too.

**Comment by begali** [comment]
@gfaiers You can still add jar file from https://repo.spring.io/plugins-release/br/com/zbra/android-linq/1.1.0/

**Comment by brunovinicius** [comment]
@begali how does that translate to the gradle file? Please post a sample so I can update the README with that info.

**Comment by begali** [comment]
@brunovinicius  Problem is with gradle version 6.1.1 not Android studio. New gradle version refusing to download the library. Gradle version 5.6.4 and gradle plugin version 3.6.2 works perfectly. But in order to work with new gradle version I downloaded jar file of library from mvnrepository.com and added it locally. First I downloaded from bintray.com, but all classes and interfaces didn't have public access modifiers, then downloaded from mvnrepository.com. I don't know why new gradle refusing to download.

**Comment by hamzaahmedkhan** [comment]
1.1.0 release tag is missing from repo. I was using this library in my project "compile 'br.com.zbra:android-linq:1.1.0'". What is the alternative?

**Comment by brunovinicius** [comment]
Hey everyone! With the help of @hamzaahmedkhan we managed to pull of an viable alternative to use the lib. 

Refer to https://jitpack.io/#zbra-solutions/android-linq/1.1.0 for instructions. I will update the ReadME accordingly

**Comment by brunovinicius** [comment]
See #30 for more details.
