### ISSUE TITLE
v1.1.0 release tag is missing

### ISSUE THREAD

**Issue by hamzaahmedkhan** [zbra-solutions/android-linq#30]
I've been using v1.1.0 release in my applications and now I am getting errors by adding this dependency in my project.
`compile 'br.com.zbra:android-linq:1.1.0'`

I've verified this on Jitpack.io and your github repo. It seems like 1.1.0 tag is missing.
If there is no quick solution then Can you provide me the commit number on which this tag was added?

**Comment by brunovinicius** [comment]
Hello! I added the tag to the repo. Can you check if its working now?

**Comment by brunovinicius** [comment]
Jitpack.io is recomending using this version ```implementation 'com.github.zbra-solutions:android-linq:1.1.0'```
Check this link to see complete instructions https://jitpack.io/#zbra-solutions/android-linq/1.1.0

**Comment by hamzaahmedkhan** [comment]
> Hello! I added the tag to the repo. Can you check if its working now?

Hi,
Yes it is working now. I really appreciate that you resolved my request. Thanks.
